
# https://medium.com/@garrick666/how-to-deploy-react-application-on-gitlab-page-with-router-ready-for-free-8b974189957
#workflow:
#  rules:
#    - if: $CI_COMMIT_BRANCH

#  rules:
#    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - build
  - deploy

build:
  image: node:15
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
    NODE_ENV: production
    PUBLIC_URL: https://tatall.pages.taltech.ee
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public